# Generated by Django 4.1.7 on 2023-05-10 10:07

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='环境名称', max_length=128, verbose_name='环境名称')),
                ('host', models.URLField(help_text='url不要以/结尾', validators=[projects.models.validate_host], verbose_name='项目主机')),
                ('db_config', models.JSONField(blank=True, help_text='json数据{\n            "host":"some.com",\n            "user": "root",\n            "password": "123456",\n            "db": "some",\n            "charset": "utf8",\n            "autocommit": True\n        }', null=True, verbose_name='数据库设置')),
                ('project', models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': '项目环境',
                'verbose_name_plural': '项目环境',
                'db_table': 'tb_environment',
            },
        ),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(fields=('name', 'project'), name='unique_env_name'),
        ),
    ]
