# Generated by Django 4.1.7 on 2023-05-11 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_interface_interface_unique_interface_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='devloper',
        ),
        migrations.AddField(
            model_name='interface',
            name='developer',
            field=models.CharField(default='', help_text='所属开发人员', max_length=128, verbose_name='所属开发人员'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='module',
            field=models.ForeignKey(help_text='所属模块', on_delete=django.db.models.deletion.PROTECT, related_name='interfaces', to='projects.module'),
        ),
    ]
