# Generated by Django 4.2 on 2023-05-31 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_remove_interface_devloper_interface_developer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='测试任务名称', max_length=200, verbose_name='任务名称')),
                ('modules', models.ManyToManyField(help_text='包含模块', to='projects.module', verbose_name='负责的模块')),
                ('project', models.ForeignKey(help_text='项目id', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试任务',
                'verbose_name_plural': '测试任务',
                'db_table': 'tb_task',
            },
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('name', 'project'), name='unique_task_name'),
        ),
    ]
