# Generated by Django 4.2 on 2023-06-01 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='测试套件名称', max_length=200, verbose_name='测试套件名称')),
                ('task', models.ForeignKey(help_text='测试任务id', on_delete=django.db.models.deletion.PROTECT, related_name='test_suits', to='testcase.task', verbose_name='测试任务')),
            ],
            options={
                'verbose_name': '测试套件',
                'verbose_name_plural': '测试套件',
                'db_table': 'tb_test_suit',
            },
        ),
        migrations.AddConstraint(
            model_name='testsuite',
            constraint=models.UniqueConstraint(fields=('name', 'task'), name='unique_testsuit_name'),
        ),
    ]
