# Generated by Django 4.2 on 2023-06-29 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_interface_devloper_interface_developer_and_more'),
        ('testcase', '0002_testsuite_testsuite_unique_testsuit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('title', models.CharField(help_text='用例名称', max_length=200, verbose_name='用例名称')),
                ('method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('head', 'head'), ('put', 'put'), ('patch', 'patch'), ('delete', 'delete'), ('connect', 'connect'), ('trace', 'trace')], default='get', help_text='请求方法', max_length=12, verbose_name='请求方法')),
                ('request', models.TextField(blank=True, help_text='json格式的字符串，可选键与requests模块发送请求的参数一致', null=True, verbose_name='请求数据')),
                ('tester', models.CharField(blank=True, help_text='编写这条用例的测试工程师', max_length=48, null=True, verbose_name='测试工程师')),
                ('marks', models.CharField(blank=True, help_text='字符串，用例标记，多个标记使用逗号隔开，例如：success,flow', max_length=200, null=True, verbose_name='标记')),
                ('status_code', models.SmallIntegerField(blank=True, help_text='请求响应状态码', null=True, verbose_name='响应状态码')),
                ('res_type', models.CharField(choices=[('JSON', 'JSON'), ('XML', 'XML'), ('HTML', 'HTML')], default='JSON', help_text='字符串，响应类型，可选值 JSON XML HTML 必须大写', max_length=24, verbose_name='响应类型')),
                ('assertion', models.TextField(blank=True, help_text='断言表达式，嵌套的数组json字符串[[期望值,条件,jsonpath提取表达式],..]，\n    例如：[[0,"eq","$..code"],["OK","eq","$..msg"]]', null=True, verbose_name='断言表达式')),
                ('db_assertion', models.TextField(blank=True, help_text='数据库断言表达式，格式同断言表达式', null=True, verbose_name='数据库断言表达式')),
                ('extract', models.TextField(blank=True, help_text='提取响应结果表达式,嵌套数组json字符串[[变量名,提取表达式],..]', null=True, verbose_name='响应结果提取数据表达式')),
                ('order', models.SmallIntegerField(blank=True, help_text='序号', null=True, verbose_name='序号')),
                ('interface', models.ForeignKey(help_text='所属接口id', on_delete=django.db.models.deletion.PROTECT, related_name='testcases', to='projects.interface', verbose_name='所属接口')),
                ('test_suit', models.ForeignKey(blank=True, help_text='所属测试套件id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcases', to='testcase.testsuite', verbose_name='所属测试套件')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'tb_test_case',
                'ordering': ['order', 'id'],
            },
        ),
    ]
