# Generated by Django 4.1.7 on 2023-05-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, error_messages={'unique': '手机号码已注册'}, help_text='手机号码', max_length=11, null=True, unique=True, verbose_name='手机号码'),
        ),
    ]
